# Generated by Django 3.1.4 on 2020-12-17 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TourDetails',
            new_name='table1',
        ),
    ]
