# Generated by Django 3.1.4 on 2020-12-18 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_auto_20201217_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table1',
            old_name='county_name',
            new_name='country_name',
        ),
    ]
